### PR TITLE
Adding pebble-time

### PR DESCRIPTION
**Pull request by gregheo**

### CODE REVIEW

**Comment by micpringle** [comment]
Hello @gregheo! Nice pull request :heart_eyes:

**Comment by gregheo** [comment]
@micpringle, do I need to blah blah blah?

**Comment by micpringle** [comment]
@gregheo DO IT! DO IT NOW!

**Comment by gregheo** [comment]
@micpringle Mic, this is ready for a tech editor!

**Comment by micpringle** [comment]
@gregheo This is ready for you to begin editing. Please open a pull request and crack on.

**Pull request merged**
